
project_id = "pklxufsqjaobntpqsqno"

[auth]
enabled = true
email_enabled = true
sms_enabled = false

[auth.external.discord]
enabled = true
client_id = "env(DISCORD_CLIENT_ID)"
secret = "env(DISCORD_CLIENT_SECRET)"

[api]
enabled = true
port = 54321

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true

[analytics]
enabled = false

[functions]
enabled = true
