
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pklxufsqjaobntpqsqno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBrbHh1ZnNxamFvYm50cHFzcW5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5NDc4MTIsImV4cCI6MjA2NzUyMzgxMn0.A68K9xms76fLZr9wkR1ftlaqAw1Ss_Bl1DC2nxvpogI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce'
  },
  global: {
    headers: {
      'X-Client-Info': 'buildfor-me-auth-v2'
    }
  }
});

// Debug logging utility
export const debugAuth = {
  log: (message: string, data?: any) => {
    console.log(`🔍 [AUTH DEBUG] ${message}`, data || '');
  },
  error: (message: string, error?: any) => {
    console.error(`❌ [AUTH ERROR] ${message}`, error || '');
  },
  success: (message: string, data?: any) => {
    console.log(`✅ [AUTH SUCCESS] ${message}`, data || '');
  }
};
